name: .NET CI + CodeQL

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-test-codeql:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp
          build-mode: manual

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore -warnaserror

      # Run ONLY unit tests project (skip benchmark)
      - name: Run unit tests
        run: dotnet test JsonParserPerformance.UnitTests/JsonParserPerformance.UnitTests.csproj --configuration Release --no-build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3